# FIXME: won't work yet, because nextest requires --locked
# - id: nextest-run
#   name: nextest-run
#   description: Run test cases with nextest
#   entry: cargo nextest run
#   language: rust
#   additional_dependencies:
#     - "cli:cargo-nextest:0.9.140"
#   types: [rust]
#   pass_filenames: false
- id: cargo-fmt
  name: cargo-fmt
  description: Format files with cargo-fmt.
  entry: cargo fmt
  language: rust
  types: [rust]
  args: ["--"]
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: rust
  types: [rust]
  pass_filenames: false
- id: clippy
  name: clippy
  description: Lint rust sources using cargo-clippy.
  entry: cargo clippy
  language: rust
  types: [rust]
  pass_filenames: false
